"""
Fleet Briefing — AI-generated executive summary for operators and maintenance teams.
Generated by e2_web_platform_agent_job (Claude Sonnet 4.6) — updated 2× per day.
"""
import os
from datetime import datetime
import streamlit as st

st.set_page_config(page_title="Fleet Briefing", layout="wide")

BRIEFINGS_DIR = r'd:\Predictive_analytics\dashboard\briefings'
CURRENT_PATH  = os.path.join(BRIEFINGS_DIR, 'current.md')

st.title(":material/description: Fleet Briefing — AI Executive Summary")
st.caption("Generated by Claude Sonnet 4.6 · Based on last 30 days of fleet data")

if not os.path.exists(CURRENT_PATH):
    st.info("No briefing available yet. The `e2_web_platform_agent_job` will generate the first report on the next scheduled run.")
    st.stop()

mtime = os.path.getmtime(CURRENT_PATH)
last_updated = datetime.fromtimestamp(mtime).strftime('%Y-%m-%d %H:%M')
st.caption(f"Last updated: **{last_updated}**")

age_seconds = (datetime.now() - datetime.fromtimestamp(mtime)).total_seconds()
age_hours = age_seconds / 3600
if age_hours < 1:
    age_label = "Generated less than an hour ago"
elif age_hours < 48:
    age_label = f"Generated {int(round(age_hours))}h ago"
else:
    age_label = f"Generated {int(age_hours // 24)} days ago"

if age_hours <= 18:
    st.success(age_label)
else:
    st.warning(f"{age_label} — pipeline may be stale")

with open(CURRENT_PATH, 'r', encoding='utf-8') as f:
    briefing = f.read()

st.markdown(briefing)

# Archive navigation
st.divider()
st.subheader(":material/summarize: Previous Briefings")
if os.path.exists(BRIEFINGS_DIR):
    files = sorted(
        [f for f in os.listdir(BRIEFINGS_DIR) if f.endswith('.md') and f != 'current.md'],
        reverse=True
    )[:10]
    if files:
        sel = st.selectbox("Select briefing", files)
        if sel:
            with open(os.path.join(BRIEFINGS_DIR, sel), 'r', encoding='utf-8') as f:
                st.markdown(f.read())
    else:
        st.caption("Only the current briefing is available.")
