"""
Fleet Briefing — AI-generated executive summary for operators and maintenance teams.
Generated by e2_web_platform_agent_job (claude-opus-4-8) — updated 2× per day.
"""
import os
import re
from datetime import datetime
import streamlit as st

st.set_page_config(page_title="Fleet Briefing", layout="wide")

BRIEFINGS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'briefings')
CURRENT_PATH  = os.path.join(BRIEFINGS_DIR, 'current.md')

st.title(":material/description: Fleet Briefing — AI Executive Summary")
st.caption("Generated by claude-opus-4-8 · Based on last 30 days of fleet data")

if not os.path.exists(CURRENT_PATH):
    st.info("No briefing available yet. The `e2_web_platform_agent_job` will generate the first report on the next scheduled run.")
    st.stop()

def _latest_briefing_time():
    """Generation time from the most-recent dated archive filename
    (e.g. 2026-05-28_1801.md). In deploy the current.md mtime is the git
    checkout time, not the generation time, so only fall back to it when
    no dated archive exists."""
    latest = None
    if os.path.exists(BRIEFINGS_DIR):
        for name in os.listdir(BRIEFINGS_DIR):
            m = re.match(r'(\d{4}-\d{2}-\d{2})_(\d{2})(\d{2})\.md', name)
            if not m:
                continue
            try:
                dt = datetime.strptime(f"{m.group(1)} {m.group(2)}:{m.group(3)}", '%Y-%m-%d %H:%M')
            except ValueError:
                continue
            if latest is None or dt > latest:
                latest = dt
    if latest is None:
        latest = datetime.fromtimestamp(os.path.getmtime(CURRENT_PATH))
    return latest

generated_at = _latest_briefing_time()
last_updated = generated_at.strftime('%Y-%m-%d %H:%M')
st.caption(f"Last updated: **{last_updated}**")

age_seconds = (datetime.now() - generated_at).total_seconds()
age_hours = age_seconds / 3600
if age_hours < 1:
    age_label = "Generated less than an hour ago"
elif age_hours < 48:
    age_label = f"Generated {int(round(age_hours))}h ago"
else:
    age_label = f"Generated {int(age_hours // 24)} days ago"

if age_hours <= 18:
    st.success(age_label)
else:
    st.warning(f"{age_label} — pipeline may be stale")

with open(CURRENT_PATH, 'r', encoding='utf-8') as f:
    briefing = f.read()

st.markdown(briefing)

# Archive navigation
st.divider()
st.subheader(":material/summarize: Previous Briefings")
if os.path.exists(BRIEFINGS_DIR):
    files = sorted(
        [f for f in os.listdir(BRIEFINGS_DIR) if f.endswith('.md') and f != 'current.md'],
        reverse=True
    )[:10]
    if files:
        sel = st.selectbox("Select briefing", files)
        if sel:
            with open(os.path.join(BRIEFINGS_DIR, sel), 'r', encoding='utf-8') as f:
                st.markdown(f.read())
    else:
        st.caption("Only the current briefing is available.")
