"""
Fleet Briefing -- AI-generated executive summary for operators and maintenance teams.
Generated by an automated agent, updated twice daily.
"""
import os
import re
from datetime import datetime, timezone
import streamlit as st

from utils.drive_loader import get_file_mtime

st.set_page_config(page_title="Fleet Briefing", layout="wide")

_CORE_PIPELINE_FILE = "e2_foqa_report.parquet"
_CORE_PIPELINE_STALE_HOURS = 48
_BRIEFING_DEAD_HOURS = 168  # 7 days -- beyond this it is a stopped job, not a delay


@st.cache_data(ttl=300, show_spinner=False)
def _core_pipeline_age_hours():
    """Age in hours of the core fleet-data pipeline output, or None if unavailable."""
    mtime = get_file_mtime(_CORE_PIPELINE_FILE)
    if mtime is None:
        return None
    return (datetime.now(timezone.utc) - mtime).total_seconds() / 3600

BRIEFINGS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'briefings')
CURRENT_PATH  = os.path.join(BRIEFINGS_DIR, 'current.md')

st.title(":material/description: Fleet Briefing -- AI Executive Summary")
st.caption("Generated by an automated agent - Based on last 30 days of fleet data")

if not os.path.exists(CURRENT_PATH):
    st.info("No briefing available yet. The first report will be generated on the next scheduled run.")
    st.stop()

def _latest_briefing_time():
    """Generation time from the most-recent dated archive filename
    (e.g. 2026-05-28_1801.md). In deploy the current.md mtime is the git
    checkout time, not the generation time, so only fall back to it when
    no dated archive exists."""
    latest = None
    if os.path.exists(BRIEFINGS_DIR):
        for name in os.listdir(BRIEFINGS_DIR):
            m = re.match(r'(\d{4}-\d{2}-\d{2})_(\d{2})(\d{2})\.md', name)
            if not m:
                continue
            try:
                dt = datetime.strptime(f"{m.group(1)} {m.group(2)}:{m.group(3)}", '%Y-%m-%d %H:%M')
            except ValueError:
                continue
            if latest is None or dt > latest:
                latest = dt
    if latest is None:
        latest = datetime.fromtimestamp(os.path.getmtime(CURRENT_PATH))
    return latest

generated_at = _latest_briefing_time()
last_updated = generated_at.strftime('%Y-%m-%d %H:%M')
st.caption(f"Last updated: **{last_updated}**")

age_seconds = (datetime.now() - generated_at).total_seconds()
age_hours = age_seconds / 3600
if age_hours < 1:
    age_label = "Generated less than an hour ago"
elif age_hours < 48:
    age_label = f"Generated {int(round(age_hours))}h ago"
else:
    age_label = f"Generated {int(age_hours // 24)} days ago"

_briefing_is_dead = age_hours > _BRIEFING_DEAD_HOURS

if _briefing_is_dead:
    st.error(
        f"{age_label} -- briefing generation has not produced a new summary in over "
        f"{int(_BRIEFING_DEAD_HOURS // 24)} days, far beyond the twice-daily schedule. "
        "The content below is no longer a reliable summary of fleet status and has "
        "been hidden. Contact data operations to restore the briefing pipeline."
    )
elif age_hours <= 18:
    st.success(age_label)
else:
    core_age_h = _core_pipeline_age_hours()
    if core_age_h is None:
        st.warning(
            f"{age_label} -- the AI summary is behind schedule, and the core fleet data "
            f"pipeline's freshness could not be checked. Treat all figures below with caution."
        )
    elif core_age_h <= _CORE_PIPELINE_STALE_HOURS:
        st.warning(
            f"{age_label} -- the AI summary generation is delayed, but the core fleet data "
            f"pipeline is current (refreshed {core_age_h:.0f}h ago). Figures below may not "
            f"reflect the most recent flights, but the underlying data pipeline is healthy."
        )
    else:
        st.error(
            f"{age_label} -- the AI summary is delayed AND the core fleet data pipeline is "
            f"also stale (last refreshed {core_age_h:.0f}h ago, threshold {_CORE_PIPELINE_STALE_HOURS}h). "
            f"This points to an underlying pipeline issue, not just a delayed summary -- contact data operations."
        )

if not _briefing_is_dead:
    with open(CURRENT_PATH, 'r', encoding='utf-8') as f:
        briefing = f.read()
    st.markdown(briefing)

# Archive navigation
st.divider()
st.subheader(":material/summarize: Previous Briefings")
if os.path.exists(BRIEFINGS_DIR):
    files = sorted(
        [f for f in os.listdir(BRIEFINGS_DIR) if f.endswith('.md') and f != 'current.md'],
        reverse=True
    )[:10]
    if files:
        sel = st.selectbox("Select briefing", files)
        if sel:
            with open(os.path.join(BRIEFINGS_DIR, sel), 'r', encoding='utf-8') as f:
                st.markdown(f.read())
    else:
        st.caption("Only the current briefing is available.")
